name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  bun:
    name: Bun
    runs-on: ubuntu-latest
    concurrency: ci-bun-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Packages
        run: bun install

      - name: Build Server
        run: bun run build
        working-directory: ./server

      - name: Build Server
        run: bun run build
        working-directory: ./client
  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency: ci-lint-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .
